services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
        - pgadmin:/var/lib/pgadmin
    ports:
        - "5050:80"
    networks:
        - postgres_network
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_container
    ports:
      - "9411:9411"
    networks:
      - postgres_network
    restart: unless-stopped

networks:
    postgres_network:
        driver: bridge

volumes:
    postgres:
    pgadmin:
