services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_container
    ports:
      - "9411:9411"
    networks:
      - postgres_network
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres_network
    restart: unless-stopped

  user-service:
    image: yaremenko/user-service:latest
    container_name: user-service
    ports:
      - "8091:8091"
    networks:
      - postgres_network
      - microservice_network
    restart: unless-stopped
    depends_on:
      - service-registry
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka

  content-service:
    image: yaremenko/content-service:latest
    container_name: content-service
    ports:
      - "8092:8092"
    networks:
      - postgres_network
      - microservice_network
    restart: unless-stopped
    depends_on:
      - service-registry
      - config-server
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka

  common-service:
    image: yaremenko/common-service:latest
    container_name: common-service
    ports:
      - "8093:8093"
    networks:
      - postgres_network
      - microservice_network
    restart: unless-stopped
    depends_on:
      - service-registry
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka

  service-registry:
    image: yaremenko/service-registry:latest
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - postgres_network
      - microservice_network
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq
      - zipkin
      - pgadmin
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  config-server:
    image: yaremenko/config-server:latest
    container_name: config-server
    ports:
      - "8088:8888"
    networks:
      - postgres_network
      - microservice_network
    restart: unless-stopped
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka

  gateway:
    image: yaremenko/gateway:latest
    container_name: gateway
    ports:
      - "8090:8090"
    networks:
      - postgres_network
      - microservice_network
    restart: unless-stopped
    depends_on:
      - service-registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka

networks:
  microservice_network:
    driver: bridge
  postgres_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
