apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 9411
          targetPort: 9411
    selector:
        app: zipkin
